server:
  port: 8082

internal:
  security:
    api-key: ${IDENTITY_INTERNAL_API_KEY:dev-internal-api-key}

spring:
  application:
    name: identity-service
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:h2:file:~/atom-shared-db;AUTO_SERVER=TRUE;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  h2:
    console:
      enabled: true
      path: /h2-console

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:postgresql://localhost:5432/atom
    username: dbuser
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC

logging:
  level:
    root: INFO
    org.springframework.security: INFO
