server:
  port: 8083

identity:
  service:
    url: http://localhost:8082

schedule:
  service:
    url: http://localhost:8080

spring:
  application:
    name: import-service
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB

logging:
  level:
    root: INFO
    org.springframework.security: INFO
